

    # config/routes.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

front_index:
  path: /front-index
  controller: App\Controller\SecurityController::index

user_registration:
    path: /register-user
    controller: App\Controller\RegistrationController::userRegistration

freelancer_registration:
    path: /register-freelancer
    controller: App\Controller\RegistrationController::freelancerRegistration


admin_dashboard:
    path: /admin_dashboard
    controller: App\Controller\AdminController::adminPage
    
user_dashboard:
    path: /user
    controller: App\Controller\UserController::UserPage
    
freelancer_dashboard:
    path: /freelancer
    controller: App\Controller\FreelancerController::freelancerPage
app_forgot_password_confirm:
    path: /forgot-password-confirm
    controller: App\Controller\SecurityController::forgotPasswordConfirm

app_2fa:
    path: /2fa
    controller: App\Controller\SecurityController::enable2FA
